### ISSUE TITLE
Have rake tasks

### ISSUE THREAD

**Issue by DavidS** [puppetlabs/maintainers#6]
It'd be great to have rake tasks, at least for validate, and maybe create (using the current user's git identity, and github remotes). The former for CI, the latter for convenience.

**Comment by garethr** [comment]
I just tried this out (https://github.com/puppetlabs/puppetlabs-image_build/commit/589c19abf9ab3f3975cb7e7573023b0cc6665f32) and was going to say the same two things:
- Rake tasks would be useful for those projects where rake is the standard entry point, it aids discovery for users
- A Rake validate_maintainers task could also be hooked into a standard `test` target or similar
- Picking up defaults from Git came to my mind as well

Good stuff.

**Comment by DavidS** [comment]
btw, I would suggest `maintainers:create` and `maintainers:validate` as task names, for proper rake namespacing.

**Comment by DavidS** [comment]
... and loading it in into puppetlabs_spec_helper is probably the way to go to deploy it to all the modules.
