### ISSUE TITLE
File format hint URL issues

### ISSUE THREAD

**Issue by garethr** [puppetlabs/maintainers#9]
The MAINTAINERS file gets a file_format value like so:

`"file_format": "This MAINTAINERS file format is described at https://github.com/puppetlabs/maintainers",`

This isn't validated and is purely informational, but I see two potential issues (which you may choose to ignore):
1. The URL doesn't point at the schema, discovering that is left as an exercise for the users. Pointing at https://github.com/puppetlabs/maintainers/blob/master/schema/MAINTAINERS.json (and maybe renaming to `schema`) might be more useful in my opinion.
2. If we ever did (ha) change the GitHub org name to puppet or something else this metadata would be incorrect. I'm wondering if we want a short link on puppet.com which we can repoint?

**Comment by kylog** [comment]
PRs #12 and #13 should resolve (1) above. I like the short link idea as well; I've requested a tinycc account and will return to that short link idea once I am so empowered.
